#!/bin/sh

[ "$(stat -c %y ~/.cache/corona/corona 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] && 
	curl -s https://corona-stats.online/Poland > .cache/corona/corona

	grep "Poland" ~/.cache/corona/corona | 
	sed "s/\s*//g ; s/║//g ; s/│/;/g ; s/\x1b\[[0-9;]*m//g ; s/,/./g ; s/▲/ /g " |  
	awk -F';' '{print  " "$3 "  " $4 }'

